### ISSUE TITLE
Debian stretch: hpacucli is no more, use ssacli

### ISSUE THREAD

**Issue by matsimon** [adfinis-sygroup/ansible-role-hwraid#2]
I've given a look at the repository structure of HPE's mcp repository for Debian stretch and following things have change from what I remember from jessie:

* hpacucli is no more, it has been replaced by ssacli
* hpssacli is now called ssacli
* ssa (Smart Storage Administration Utility) is now available like already referenced in RedHat.yml. It may have already been there with jessie, haven't check though.

Proposal: Either update Debian.yml to acommodate for Debian 9 (and add Debian_8.yml) or add Debian_9.yml. Personally I'd opt for an updated Debian.yml and add a Debian_8.yml instead.

What's your take?

**Comment by keachi** [comment]
That's a good decision. The `debian.yml` should be for the actual stable version and for any older version we create a file if needed. If we drop support for e.g. debian 7 we can just remove all `debian7.yml` files.

**Comment by karras** [comment]
This has been fixed by #3 right?

**Comment by keachi** [comment]
I think so, but there was no comment like `Fix #3`. What do you say @matsimon?

**Comment by matsimon** [comment]
That was intended. We should document the added variable hwraid_hp_repository_version in our Readme and then close the issue.

I'll have to check what Galaxy wants for a format to be rendered correctly.
